on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Benchmark API REST
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Hello world action step
        uses: econesag/api_benchmark@main
        id: benchmark
        env:
          config: config_error.yaml